# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np

### 1. Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [5]:
A = np.arange(1, 16).reshape(3,5)

In [6]:
print("Matrix A:")
print(A)

print("Dimension (ndim):", A.ndim)       # Number of axes
print("Shape:", A.shape)                 # Shape of the array (rows, columns)
print("Size:", A.size)                   # Total number of elements
print("Data type (dtype):", A.dtype)     # Data type of the elements

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimension (ndim): 2
Shape: (3, 5)
Size: 15
Data type (dtype): int32


### 2. Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [8]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print("B =\n", B)
print("\nC =\n", C)

B =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

C =
 [[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [9]:
B - C #Elementwise subtraction

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [10]:
B * C #Elementwise multiplication

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [11]:
B @ C #Matrix multiplication

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### 3. Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [13]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
np.exp(B) #Elementwise exponentiation

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [15]:
np.min(B) #Minimum value in the matrix

1

In [16]:
np.min(B, axis=1) #Minimum value in each row

array([1, 4, 7])

In [17]:
np.min(B, axis=0) #Minimum value in each column

array([1, 2, 3])

In [18]:
np.argmin(B) #Index of the minimum value in the whole matrix

0

In [19]:
np.argmin(B, axis=1) #Index of the minimum value in each row

array([0, 0, 0], dtype=int64)

In [20]:
np.sum(B) #Sum of all elements

45

In [21]:
np.mean(B, axis=0) #Mean of each column

array([4., 5., 6.])

In [22]:
np.median(B, axis=0) #Median of each column

array([4., 5., 6.])

### 4. What does it mean when you provide fewer indices than axes when slicing? See example below.

In [24]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [25]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

You're generally slicing along the leading axes, and the remaining axes are left unsliced, meaning the result will include the full range along those remaining axes.

### 5. Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [29]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [31]:
for element in np.nditer(A): #This iterates efficiently over every element, regardless of the shape
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### 6. Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [33]:
a = np.arange(30) #This creates a 1D NumPy array with values from 0 to 29 (30 elements total):
b = a.reshape((2, 3, -1)) #You're reshaping a into a new array b with shape (2, 3, -1). Here, -1 tells NumPy to automatically calculate the appropriate size for that axis, based on the total number of elements (30 in this case).
print(a) 
print()

print(b) #b is a 3-dimensional array (or tensor).

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [38]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [40]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [41]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [84]:
import numpy as np

def add_mult_matrices(matrix1, matrix2, operation):
    # Validate that both inputs are numpy arrays
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise TypeError("Both matrix1 and matrix2 must be of type numpy.ndarray.")

    # Validate that the operation is either 'add' or 'multiply'
    if operation not in ['add', 'multiply']:
        raise ValueError("The operation must be either 'add' or 'multiply'.")

    if operation == 'add':
        # Validate same shape for addition
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition.")
        return matrix1 + matrix2

    elif operation == 'multiply':
        # Validate conforming shapes for matrix multiplication
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must equal the number of rows in the second matrix for multiplication.")
        return np.dot(matrix1, matrix2)

In [86]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Addition
print(add_mult_matrices(A, B, 'add'))

# Multiplication
print(add_mult_matrices(A, B, 'multiply'))

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

done

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

done

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [48]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [49]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [50]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
